spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectcitp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: springboot
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

mybatis:
  type-aliases-package: com.example.pojo
  mapper-locations: "classpath*:mapper/*.xml"

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql